// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCade.Data;

namespace NetCade.Data.Migrations
{
    [DbContext(typeof(NetCadeContext))]
    [Migration("20200302022541_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("NetCade.Models.UserAccount", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnName("UserAccountName")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Name = "Greg",
                            Password = "1234",
                            UserName = "FuckMeInAss"
                        },
                        new
                        {
                            Name = "Carrot Cake",
                            Password = "899",
                            UserName = "Mini-carrot cake"
                        },
                        new
                        {
                            Name = "Cake",
                            Password = "L0L",
                            UserName = "ThatAss"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
